version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poc_db # Crée automatiquement une base de données
    volumes:
      - './data:/var/lib/mysql'
      - './database/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '3306:3306' # Port par défaut pour MySQL

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=dracula
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '80:80'
    depends_on:
      - adminer
      
